### PR TITLE
Passing in URIs to Gdal and GdalReader

### PR DESCRIPTION
**Pull request by jbouffard**
This PR makes it so that users can pass in either paths or `URI`s to `Gdal` and `GdalReader`. This was done by creating the `URIFormatter` object which formats the given path/`URI` in such a way that GDAL can read it.

The backends that are supported with this PR:
- Local Filesystem
- Hdfs
- S3
- Azure
- Google Cloud Storage
- HTTP/HTTPS/FTP

In additions to the supported backends, various compressed filetypes can be read from as well:
- zip
- kmz
- ods
- xlsx
- gzip
- tar
- tgz

**Note:** This PR introduces ways to format a given URI; however, it does nothing with setting permissions. Therefore, it is assumed the user setup their environment such that GDAL can access the needed credentials.

### CODE REVIEW

**Comment by pomadchin** [comment]
@jbouffard i thouhgt that we've decided not to touch geotrellis-gdal, as it can slow down development. The idea is to push geotrellis-contrib until smth stable would be done, and only after that to move code ino geotrellis-gdal; otherwise there would be too much inconvinience in new features introduction, for instance: 1. introduce changes into geotrellis-contirb 2. it requires changes to be introduced into geotrellis-gdal 3, we again need to fix geotrellis-contrib.

In addition, it looks like we need this code now in geotrellis-contrib. @echeipesh what do you think about it?

**Comment by jbouffard** [comment]
@pomadchin My reasoning for making a PR against `geotrells-gdal` was this line in the description of the task:

> This translation should be a standard behavior and therefore it should happen in geotrellis-gdal library.

Otherwise, I agree with you that it'd makes more sense to have this PR be against `geotrellis-contrib`.

**Comment by jbouffard** [comment]
Though, I should mention that this work can be pretty easily ported over to `geotrellis-contrb`.

**Comment by echeipesh** [comment]
Whoops, that task was split into two "do it in geotrellis-costrib" and "do it in geotrellis-gdal" after the conclusion that its too early to port work from `geotrellis-contrib` and make it depend on `geotrellis-gdal`. 

Since the work is done I think we can duplicate the PR and de-dupe it when we're ready to make `geotrellis-contrib` depend on `geotrellis-gdal`.

**Comment by jbouffard** [comment]
@echeipesh That sounds good to me. I'll work on making a PR for `geotrllis-contrib` in a little bit.

**Comment by pomadchin** [comment]
Is covered by https://github.com/geotrellis/geotrellis-gdal/pull/23

**Pull request closed without merging**
