### PR TITLE
Update versions to most recent

### PR DESCRIPTION
**Pull request by jpolchlo**
Updated some software versions.  Made Scala and SBT versions match those in use in GT.

### CODE REVIEW

**Comment by pomadchin** [comment]
@jpolchlo can you also set travis working through it?

**Comment by echeipesh** [comment]
@pomadchin Its actually not possible to run the tests through docker right now. I'm not sure how you would do that. I think its possible to set it up through https://github.com/Tapad/sbt-docker-compose but I'd leave that to a separate PR.

**Comment by pomadchin** [comment]
@echeipesh why sbt-docker-compose is required? I think the right way to publish container and to run tests like it is done for PDAL: https://github.com/PDAL/java/blob/master/.travis/run.sh

But i agree that probably it's a questions of a separate PR // though i thought that this change was initially and already introduced by Nathan.

**Comment by echeipesh** [comment]
I thought you were talking about running the `geotrellis-gdal` tests in the docker environment so it could find the native libs.

**Comment by echeipesh** [comment]
@jpolchlo If you have the container built could you push it into `quay.io/geotrellis/gdal:2.3.1` ?

**Comment by jpolchlo** [comment]
Just need to get access to the quay repo, and I can push it up

**Pull request merged**
